if(WIN32)
    add_compile_definitions(SLOTHDB_WINDOWS)
elseif(APPLE)
    add_compile_definitions(SLOTHDB_MACOS)
elseif(UNIX)
    add_compile_definitions(SLOTHDB_LINUX)
endif()

include(TestBigEndian)
test_big_endian(SLOTHDB_IS_BIG_ENDIAN)
if(SLOTHDB_IS_BIG_ENDIAN)
    add_compile_definitions(SLOTHDB_BIG_ENDIAN)
else()
    add_compile_definitions(SLOTHDB_LITTLE_ENDIAN)
endif()
